syntax = "proto3";
package warzonecore.warzone.v1;

option go_package = "github.com/Davi-UEFS/Warzone/warzone-core/x/warzone/types";

// Mission defines the Mission message.
message Mission {
  uint64 id = 1;      // O ID da requisição. Este é o criado pela blockchain.
  string sector = 2;  // O setor que criou ela.
  string status = 3;  // Status (pendente, em progresso ou concluída).
  int64 priority = 4;   // Prioridade
  string assigned_drone_id = 5; // Drone encarregado 
  string creator = 6;   // Criador do bloco (o setor)
  string reqType = 7;   // Tipo da requisição
  string coord = 8;     // Coordenadas
  int64 createdAt = 9;  // Quando foi criada.
}
