// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: warzonecore/warzone/v1/laudo.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Laudo defines the Laudo message.
type Laudo struct {
	RequisitionId string `protobuf:"bytes,1,opt,name=requisition_id,json=requisitionId,proto3" json:"requisition_id,omitempty"`
	DroneId       string `protobuf:"bytes,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Relatorio     string `protobuf:"bytes,3,opt,name=relatorio,proto3" json:"relatorio,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Creator       string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Laudo) Reset()         { *m = Laudo{} }
func (m *Laudo) String() string { return proto.CompactTextString(m) }
func (*Laudo) ProtoMessage()    {}
func (*Laudo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebb9135d03a3505, []int{0}
}
func (m *Laudo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Laudo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Laudo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Laudo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Laudo.Merge(m, src)
}
func (m *Laudo) XXX_Size() int {
	return m.Size()
}
func (m *Laudo) XXX_DiscardUnknown() {
	xxx_messageInfo_Laudo.DiscardUnknown(m)
}

var xxx_messageInfo_Laudo proto.InternalMessageInfo

func (m *Laudo) GetRequisitionId() string {
	if m != nil {
		return m.RequisitionId
	}
	return ""
}

func (m *Laudo) GetDroneId() string {
	if m != nil {
		return m.DroneId
	}
	return ""
}

func (m *Laudo) GetRelatorio() string {
	if m != nil {
		return m.Relatorio
	}
	return ""
}

func (m *Laudo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Laudo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Laudo)(nil), "warzonecore.warzone.v1.Laudo")
}

func init() {
	proto.RegisterFile("warzonecore/warzone/v1/laudo.proto", fileDescriptor_bebb9135d03a3505)
}

var fileDescriptor_bebb9135d03a3505 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x4f, 0x2c, 0xaa,
	0xca, 0xcf, 0x4b, 0x4d, 0xce, 0x2f, 0x4a, 0xd5, 0x87, 0xb2, 0xf5, 0xcb, 0x0c, 0xf5, 0x73, 0x12,
	0x4b, 0x53, 0xf2, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xc4, 0x90, 0xd4, 0xe8, 0x41, 0xd9,
	0x7a, 0x65, 0x86, 0x4a, 0x33, 0x19, 0xb9, 0x58, 0x7d, 0x40, 0xea, 0x84, 0x54, 0xb9, 0xf8, 0x8a,
	0x52, 0x0b, 0x4b, 0x33, 0x8b, 0x33, 0x4b, 0x32, 0xf3, 0xf3, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x78, 0x91, 0x44, 0x3d, 0x53, 0x84, 0x24, 0xb9, 0x38, 0x52, 0x8a, 0xf2,
	0xf3, 0x52, 0x41, 0x0a, 0x98, 0xc0, 0x0a, 0xd8, 0xc1, 0x7c, 0xcf, 0x14, 0x21, 0x19, 0x2e, 0xce,
	0xa2, 0xd4, 0x9c, 0xc4, 0x92, 0xfc, 0xa2, 0xcc, 0x7c, 0x09, 0x66, 0xb0, 0x1c, 0x42, 0x40, 0x48,
	0x8c, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x58, 0x82, 0x05, 0x2c, 0x05, 0xe5, 0x09, 0x49,
	0x70, 0xb1, 0x27, 0x17, 0xa5, 0x82, 0x14, 0x49, 0xb0, 0x42, 0xcc, 0x83, 0x72, 0x9d, 0x82, 0x4f,
	0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18,
	0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x32, 0x3d, 0xb3, 0x24, 0xa3, 0x34,
	0x49, 0x2f, 0x39, 0x3f, 0x57, 0xdf, 0x25, 0xb1, 0x2c, 0x53, 0x37, 0xd4, 0xd5, 0x2d, 0x58, 0x3f,
	0x1c, 0xea, 0x75, 0xa8, 0xf7, 0x74, 0xc1, 0xe1, 0x51, 0x01, 0x0f, 0x91, 0x92, 0xca, 0x82, 0xd4,
	0xe2, 0x24, 0x36, 0x70, 0x78, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x82, 0x30, 0x09, 0x6c,
	0x35, 0x01, 0x00, 0x00,
}

func (m *Laudo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Laudo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Laudo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLaudo(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintLaudo(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Relatorio) > 0 {
		i -= len(m.Relatorio)
		copy(dAtA[i:], m.Relatorio)
		i = encodeVarintLaudo(dAtA, i, uint64(len(m.Relatorio)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DroneId) > 0 {
		i -= len(m.DroneId)
		copy(dAtA[i:], m.DroneId)
		i = encodeVarintLaudo(dAtA, i, uint64(len(m.DroneId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RequisitionId) > 0 {
		i -= len(m.RequisitionId)
		copy(dAtA[i:], m.RequisitionId)
		i = encodeVarintLaudo(dAtA, i, uint64(len(m.RequisitionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLaudo(dAtA []byte, offset int, v uint64) int {
	offset -= sovLaudo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Laudo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequisitionId)
	if l > 0 {
		n += 1 + l + sovLaudo(uint64(l))
	}
	l = len(m.DroneId)
	if l > 0 {
		n += 1 + l + sovLaudo(uint64(l))
	}
	l = len(m.Relatorio)
	if l > 0 {
		n += 1 + l + sovLaudo(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovLaudo(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLaudo(uint64(l))
	}
	return n
}

func sovLaudo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLaudo(x uint64) (n int) {
	return sovLaudo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Laudo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLaudo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Laudo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Laudo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequisitionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaudo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaudo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaudo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequisitionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DroneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaudo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaudo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaudo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DroneId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relatorio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaudo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaudo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaudo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relatorio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaudo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaudo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaudo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLaudo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLaudo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLaudo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLaudo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLaudo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLaudo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLaudo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLaudo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLaudo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLaudo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLaudo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLaudo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLaudo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLaudo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLaudo = fmt.Errorf("proto: unexpected end of group")
)
