// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: warzonecore/warzone/v1/mission.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Mission defines the Mission message.
type Mission struct {
	Id              uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sector          string `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Status          string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Priority        int64  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	AssignedDroneId string `protobuf:"bytes,5,opt,name=assigned_drone_id,json=assignedDroneId,proto3" json:"assigned_drone_id,omitempty"`
	Creator         string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	ReqType         string `protobuf:"bytes,7,opt,name=reqType,proto3" json:"reqType,omitempty"`
	Coord           string `protobuf:"bytes,8,opt,name=coord,proto3" json:"coord,omitempty"`
	CreatedAt       int64  `protobuf:"varint,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (m *Mission) Reset()         { *m = Mission{} }
func (m *Mission) String() string { return proto.CompactTextString(m) }
func (*Mission) ProtoMessage()    {}
func (*Mission) Descriptor() ([]byte, []int) {
	return fileDescriptor_31927a9c9e7629f0, []int{0}
}
func (m *Mission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Mission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Mission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Mission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mission.Merge(m, src)
}
func (m *Mission) XXX_Size() int {
	return m.Size()
}
func (m *Mission) XXX_DiscardUnknown() {
	xxx_messageInfo_Mission.DiscardUnknown(m)
}

var xxx_messageInfo_Mission proto.InternalMessageInfo

func (m *Mission) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Mission) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *Mission) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Mission) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Mission) GetAssignedDroneId() string {
	if m != nil {
		return m.AssignedDroneId
	}
	return ""
}

func (m *Mission) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Mission) GetReqType() string {
	if m != nil {
		return m.ReqType
	}
	return ""
}

func (m *Mission) GetCoord() string {
	if m != nil {
		return m.Coord
	}
	return ""
}

func (m *Mission) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Mission)(nil), "warzonecore.warzone.v1.Mission")
}

func init() {
	proto.RegisterFile("warzonecore/warzone/v1/mission.proto", fileDescriptor_31927a9c9e7629f0)
}

var fileDescriptor_31927a9c9e7629f0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0x97, 0x6e, 0x6b, 0xd7, 0x1c, 0x14, 0x83, 0x8c, 0x20, 0x12, 0x8a, 0x78, 0x28, 0xc2,
	0x5a, 0x8a, 0x4f, 0xa0, 0x4c, 0x41, 0xc4, 0x4b, 0xd5, 0x8b, 0x97, 0xd1, 0x35, 0x61, 0xe6, 0xb0,
	0xa6, 0x26, 0x59, 0xb5, 0x3e, 0x85, 0x8f, 0xe5, 0x71, 0x47, 0x8f, 0xd2, 0x3e, 0x85, 0x37, 0x69,
	0xda, 0x4e, 0x6f, 0xdf, 0xef, 0xf7, 0xfd, 0x3f, 0x12, 0xfe, 0xf0, 0xf4, 0x35, 0x91, 0xef, 0x22,
	0x63, 0xa9, 0x90, 0x2c, 0xec, 0xe6, 0xb0, 0x88, 0xc2, 0x35, 0x57, 0x8a, 0x8b, 0x2c, 0xc8, 0xa5,
	0xd0, 0x02, 0x4d, 0xff, 0xa5, 0x82, 0x6e, 0x0e, 0x8a, 0xe8, 0xe4, 0x07, 0x40, 0xe7, 0xae, 0x4d,
	0xa2, 0x3d, 0x68, 0x71, 0x8a, 0x81, 0x07, 0xfc, 0x51, 0x6c, 0x71, 0x8a, 0xa6, 0xd0, 0x56, 0x2c,
	0xd5, 0x42, 0x62, 0xcb, 0x03, 0xbe, 0x1b, 0x77, 0x64, 0xbc, 0x4e, 0xf4, 0x46, 0xe1, 0x61, 0xe7,
	0x0d, 0xa1, 0x23, 0x38, 0xc9, 0x25, 0x17, 0x92, 0xeb, 0x12, 0x8f, 0x3c, 0xe0, 0x0f, 0xe3, 0x1d,
	0xa3, 0x33, 0x78, 0x90, 0x28, 0xc5, 0x57, 0x19, 0xa3, 0x0b, 0x2a, 0x45, 0xc6, 0x16, 0x9c, 0xe2,
	0xb1, 0x39, 0xdf, 0xef, 0x17, 0xf3, 0xc6, 0xdf, 0x50, 0x84, 0xa1, 0x93, 0x4a, 0x96, 0x34, 0x0f,
	0xdb, 0x26, 0xd1, 0x63, 0xb3, 0x91, 0xec, 0xe5, 0xa1, 0xcc, 0x19, 0x76, 0xda, 0x4d, 0x87, 0xe8,
	0x10, 0x8e, 0x53, 0x21, 0x24, 0xc5, 0x13, 0xe3, 0x5b, 0x40, 0xc7, 0xd0, 0x35, 0xa7, 0x8c, 0x5e,
	0x68, 0xec, 0x9a, 0x2f, 0xfd, 0x89, 0xcb, 0xdb, 0xcf, 0x8a, 0x80, 0x6d, 0x45, 0xc0, 0x77, 0x45,
	0xc0, 0x47, 0x4d, 0x06, 0xdb, 0x9a, 0x0c, 0xbe, 0x6a, 0x32, 0x78, 0x8a, 0x56, 0x5c, 0x3f, 0x6f,
	0x96, 0x41, 0x2a, 0xd6, 0xe1, 0x3c, 0x29, 0xf8, 0xec, 0xf1, 0xea, 0xfa, 0xbe, 0x2f, 0x77, 0x66,
	0x9a, 0x7e, 0xdb, 0x75, 0xad, 0xcb, 0x9c, 0xa9, 0xa5, 0x6d, 0x7a, 0x3e, 0xff, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0x39, 0x36, 0x3a, 0x8f, 0x01, 0x00, 0x00,
}

func (m *Mission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Mission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Mission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintMission(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Coord) > 0 {
		i -= len(m.Coord)
		copy(dAtA[i:], m.Coord)
		i = encodeVarintMission(dAtA, i, uint64(len(m.Coord)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ReqType) > 0 {
		i -= len(m.ReqType)
		copy(dAtA[i:], m.ReqType)
		i = encodeVarintMission(dAtA, i, uint64(len(m.ReqType)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMission(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AssignedDroneId) > 0 {
		i -= len(m.AssignedDroneId)
		copy(dAtA[i:], m.AssignedDroneId)
		i = encodeVarintMission(dAtA, i, uint64(len(m.AssignedDroneId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Priority != 0 {
		i = encodeVarintMission(dAtA, i, uint64(m.Priority))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintMission(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sector) > 0 {
		i -= len(m.Sector)
		copy(dAtA[i:], m.Sector)
		i = encodeVarintMission(dAtA, i, uint64(len(m.Sector)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintMission(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMission(dAtA []byte, offset int, v uint64) int {
	offset -= sovMission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Mission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMission(uint64(m.Id))
	}
	l = len(m.Sector)
	if l > 0 {
		n += 1 + l + sovMission(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovMission(uint64(l))
	}
	if m.Priority != 0 {
		n += 1 + sovMission(uint64(m.Priority))
	}
	l = len(m.AssignedDroneId)
	if l > 0 {
		n += 1 + l + sovMission(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMission(uint64(l))
	}
	l = len(m.ReqType)
	if l > 0 {
		n += 1 + l + sovMission(uint64(l))
	}
	l = len(m.Coord)
	if l > 0 {
		n += 1 + l + sovMission(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovMission(uint64(m.CreatedAt))
	}
	return n
}

func sovMission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMission(x uint64) (n int) {
	return sovMission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Mission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Mission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Mission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			m.Priority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priority |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignedDroneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssignedDroneId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReqType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReqType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coord", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coord = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMission = fmt.Errorf("proto: unexpected end of group")
)
