// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: warzonecore/warzone/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetDroneRequest defines the QueryGetDroneRequest message.
type QueryGetDroneRequest struct {
	DroneId string `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
}

func (m *QueryGetDroneRequest) Reset()         { *m = QueryGetDroneRequest{} }
func (m *QueryGetDroneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDroneRequest) ProtoMessage()    {}
func (*QueryGetDroneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{2}
}
func (m *QueryGetDroneRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDroneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDroneRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDroneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDroneRequest.Merge(m, src)
}
func (m *QueryGetDroneRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDroneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDroneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDroneRequest proto.InternalMessageInfo

func (m *QueryGetDroneRequest) GetDroneId() string {
	if m != nil {
		return m.DroneId
	}
	return ""
}

// QueryGetDroneResponse defines the QueryGetDroneResponse message.
type QueryGetDroneResponse struct {
	Drone Drone `protobuf:"bytes,1,opt,name=drone,proto3" json:"drone"`
}

func (m *QueryGetDroneResponse) Reset()         { *m = QueryGetDroneResponse{} }
func (m *QueryGetDroneResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDroneResponse) ProtoMessage()    {}
func (*QueryGetDroneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{3}
}
func (m *QueryGetDroneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDroneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDroneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDroneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDroneResponse.Merge(m, src)
}
func (m *QueryGetDroneResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDroneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDroneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDroneResponse proto.InternalMessageInfo

func (m *QueryGetDroneResponse) GetDrone() Drone {
	if m != nil {
		return m.Drone
	}
	return Drone{}
}

// QueryAllDroneRequest defines the QueryAllDroneRequest message.
type QueryAllDroneRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDroneRequest) Reset()         { *m = QueryAllDroneRequest{} }
func (m *QueryAllDroneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDroneRequest) ProtoMessage()    {}
func (*QueryAllDroneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{4}
}
func (m *QueryAllDroneRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDroneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDroneRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDroneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDroneRequest.Merge(m, src)
}
func (m *QueryAllDroneRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDroneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDroneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDroneRequest proto.InternalMessageInfo

func (m *QueryAllDroneRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllDroneResponse defines the QueryAllDroneResponse message.
type QueryAllDroneResponse struct {
	Drone      []Drone             `protobuf:"bytes,1,rep,name=drone,proto3" json:"drone"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDroneResponse) Reset()         { *m = QueryAllDroneResponse{} }
func (m *QueryAllDroneResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDroneResponse) ProtoMessage()    {}
func (*QueryAllDroneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{5}
}
func (m *QueryAllDroneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDroneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDroneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDroneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDroneResponse.Merge(m, src)
}
func (m *QueryAllDroneResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDroneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDroneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDroneResponse proto.InternalMessageInfo

func (m *QueryAllDroneResponse) GetDrone() []Drone {
	if m != nil {
		return m.Drone
	}
	return nil
}

func (m *QueryAllDroneResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetMissionRequest defines the QueryGetMissionRequest message.
type QueryGetMissionRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetMissionRequest) Reset()         { *m = QueryGetMissionRequest{} }
func (m *QueryGetMissionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMissionRequest) ProtoMessage()    {}
func (*QueryGetMissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{6}
}
func (m *QueryGetMissionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMissionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMissionRequest.Merge(m, src)
}
func (m *QueryGetMissionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMissionRequest proto.InternalMessageInfo

func (m *QueryGetMissionRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryGetMissionResponse defines the QueryGetMissionResponse message.
type QueryGetMissionResponse struct {
	Mission Mission `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission"`
}

func (m *QueryGetMissionResponse) Reset()         { *m = QueryGetMissionResponse{} }
func (m *QueryGetMissionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMissionResponse) ProtoMessage()    {}
func (*QueryGetMissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{7}
}
func (m *QueryGetMissionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMissionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMissionResponse.Merge(m, src)
}
func (m *QueryGetMissionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMissionResponse proto.InternalMessageInfo

func (m *QueryGetMissionResponse) GetMission() Mission {
	if m != nil {
		return m.Mission
	}
	return Mission{}
}

// QueryAllMissionRequest defines the QueryAllMissionRequest message.
type QueryAllMissionRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMissionRequest) Reset()         { *m = QueryAllMissionRequest{} }
func (m *QueryAllMissionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMissionRequest) ProtoMessage()    {}
func (*QueryAllMissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{8}
}
func (m *QueryAllMissionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMissionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMissionRequest.Merge(m, src)
}
func (m *QueryAllMissionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMissionRequest proto.InternalMessageInfo

func (m *QueryAllMissionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllMissionResponse defines the QueryAllMissionResponse message.
type QueryAllMissionResponse struct {
	Mission    []Mission           `protobuf:"bytes,1,rep,name=mission,proto3" json:"mission"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMissionResponse) Reset()         { *m = QueryAllMissionResponse{} }
func (m *QueryAllMissionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMissionResponse) ProtoMessage()    {}
func (*QueryAllMissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53f12bb2cf7a5ab1, []int{9}
}
func (m *QueryAllMissionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMissionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMissionResponse.Merge(m, src)
}
func (m *QueryAllMissionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMissionResponse proto.InternalMessageInfo

func (m *QueryAllMissionResponse) GetMission() []Mission {
	if m != nil {
		return m.Mission
	}
	return nil
}

func (m *QueryAllMissionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "warzonecore.warzone.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "warzonecore.warzone.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetDroneRequest)(nil), "warzonecore.warzone.v1.QueryGetDroneRequest")
	proto.RegisterType((*QueryGetDroneResponse)(nil), "warzonecore.warzone.v1.QueryGetDroneResponse")
	proto.RegisterType((*QueryAllDroneRequest)(nil), "warzonecore.warzone.v1.QueryAllDroneRequest")
	proto.RegisterType((*QueryAllDroneResponse)(nil), "warzonecore.warzone.v1.QueryAllDroneResponse")
	proto.RegisterType((*QueryGetMissionRequest)(nil), "warzonecore.warzone.v1.QueryGetMissionRequest")
	proto.RegisterType((*QueryGetMissionResponse)(nil), "warzonecore.warzone.v1.QueryGetMissionResponse")
	proto.RegisterType((*QueryAllMissionRequest)(nil), "warzonecore.warzone.v1.QueryAllMissionRequest")
	proto.RegisterType((*QueryAllMissionResponse)(nil), "warzonecore.warzone.v1.QueryAllMissionResponse")
}

func init() {
	proto.RegisterFile("warzonecore/warzone/v1/query.proto", fileDescriptor_53f12bb2cf7a5ab1)
}

var fileDescriptor_53f12bb2cf7a5ab1 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0x69, 0x9b, 0xb6, 0x53, 0x10, 0x1c, 0x6b, 0xd5, 0xa0, 0x5b, 0x19, 0x45, 0x6b,
	0xda, 0xee, 0xb8, 0x2d, 0x22, 0xc5, 0x83, 0xb4, 0xd4, 0x16, 0x41, 0xa1, 0x6e, 0x11, 0xa5, 0x07,
	0x75, 0xd2, 0x2c, 0xeb, 0x42, 0xb2, 0xb3, 0xdd, 0xdd, 0x44, 0x6b, 0xf1, 0xe2, 0x27, 0x10, 0xf4,
	0xa4, 0x37, 0x15, 0xf1, 0xd8, 0x8f, 0xd1, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0x44, 0xf0, 0x6b, 0xc8,
	0xce, 0xbc, 0x35, 0xd9, 0x24, 0x6b, 0xb6, 0xd0, 0x4b, 0x98, 0x6c, 0xde, 0xff, 0xbd, 0xdf, 0x7b,
	0x6f, 0xfe, 0x1b, 0x4c, 0x5f, 0x70, 0xff, 0x95, 0x70, 0xad, 0x6d, 0xe1, 0x5b, 0x0c, 0xce, 0xac,
	0x61, 0xb0, 0x9d, 0xba, 0xe5, 0xef, 0xea, 0x9e, 0x2f, 0x42, 0x41, 0xa6, 0x3a, 0x62, 0x74, 0x38,
	0xeb, 0x0d, 0xa3, 0x78, 0x92, 0xd7, 0x1c, 0x57, 0x30, 0xf9, 0xa9, 0x42, 0x8b, 0xa5, 0x6d, 0x11,
	0xd4, 0x44, 0xc0, 0xca, 0x3c, 0xb0, 0x54, 0x0e, 0xd6, 0x30, 0xca, 0x56, 0xc8, 0x0d, 0xe6, 0x71,
	0xdb, 0x71, 0x79, 0xe8, 0x08, 0x17, 0x62, 0x27, 0x6d, 0x61, 0x0b, 0x79, 0x64, 0xd1, 0x09, 0x9e,
	0x9e, 0xb7, 0x85, 0xb0, 0xab, 0x16, 0xe3, 0x9e, 0xc3, 0xb8, 0xeb, 0x8a, 0x50, 0x4a, 0x02, 0xf8,
	0x35, 0x0d, 0xb7, 0xe2, 0x47, 0x4c, 0x2a, 0xe6, 0x72, 0x4a, 0x4c, 0xcd, 0x09, 0x82, 0x76, 0xf5,
	0x4b, 0x29, 0x51, 0x1e, 0xf7, 0x79, 0x0d, 0xca, 0xd1, 0x49, 0x4c, 0x1e, 0x44, 0x4d, 0x6c, 0xc8,
	0x87, 0xa6, 0xb5, 0x53, 0xb7, 0x82, 0x90, 0x3e, 0xc6, 0xa7, 0x12, 0x4f, 0x03, 0x4f, 0xb8, 0x81,
	0x45, 0x96, 0x71, 0x41, 0x89, 0xcf, 0xa2, 0x8b, 0x68, 0x66, 0x62, 0x41, 0xd3, 0xfb, 0xcf, 0x4d,
	0x57, 0xba, 0x95, 0xf1, 0x83, 0x9f, 0xd3, 0xb9, 0x6f, 0x7f, 0xf6, 0x4b, 0xc8, 0x04, 0x21, 0x35,
	0xf0, 0xa4, 0xcc, 0xbc, 0x6e, 0x85, 0xab, 0x51, 0x47, 0x50, 0x91, 0x9c, 0xc3, 0x63, 0xb2, 0xc3,
	0xa7, 0x4e, 0x45, 0x26, 0x1f, 0x37, 0x47, 0xe5, 0xf7, 0xbb, 0x15, 0x6a, 0xe2, 0xd3, 0x5d, 0x12,
	0xc0, 0x59, 0xc2, 0x23, 0x32, 0x06, 0x68, 0x2e, 0xa4, 0xd1, 0x48, 0xd5, 0xca, 0x70, 0x04, 0x63,
	0x2a, 0x05, 0x7d, 0x02, 0x18, 0xcb, 0xd5, 0x6a, 0x02, 0x63, 0x0d, 0xe3, 0xf6, 0x16, 0x21, 0xef,
	0x15, 0x5d, 0xad, 0x5c, 0x8f, 0x56, 0xae, 0xab, 0x6b, 0x03, 0x2b, 0xd7, 0x37, 0xb8, 0x1d, 0x6b,
	0xcd, 0x0e, 0x25, 0xfd, 0x88, 0x00, 0xba, 0x5d, 0xa0, 0x17, 0x7a, 0xe8, 0x68, 0xd0, 0x64, 0x3d,
	0x01, 0x97, 0x97, 0x70, 0x57, 0x07, 0xc2, 0xa9, 0xba, 0x09, 0xba, 0x19, 0x3c, 0x15, 0x4f, 0xf4,
	0xbe, 0xba, 0x32, 0x71, 0xff, 0x27, 0x70, 0x1e, 0x16, 0x30, 0x6c, 0xe6, 0x9d, 0x0a, 0xdd, 0xc2,
	0x67, 0x7a, 0x22, 0xa1, 0x91, 0xdb, 0x78, 0x14, 0xee, 0x1b, 0xcc, 0x69, 0x3a, 0xad, 0x15, 0x50,
	0x42, 0x33, 0xb1, 0x8a, 0x3e, 0x03, 0x8a, 0xe5, 0x6a, 0xb5, 0x8b, 0xe2, 0xb8, 0xb6, 0xf0, 0x19,
	0x01, 0x7e, 0x67, 0x89, 0x7e, 0xf8, 0x43, 0x47, 0xc7, 0x3f, 0xb6, 0x6d, 0x2c, 0xec, 0x17, 0xf0,
	0x88, 0xa4, 0x24, 0xef, 0x11, 0x2e, 0x28, 0xeb, 0x90, 0x52, 0x1a, 0x4d, 0xaf, 0x5b, 0x8b, 0xb3,
	0x99, 0x62, 0x55, 0x65, 0x6a, 0xbc, 0xf9, 0xfe, 0xfb, 0x5d, 0x7e, 0x96, 0x5c, 0x63, 0xab, 0xbc,
	0xe1, 0xcc, 0x3f, 0xbc, 0xb3, 0xb6, 0x19, 0xbf, 0x1c, 0xe6, 0xfb, 0xbf, 0x29, 0xc8, 0x17, 0x84,
	0xc7, 0x62, 0xf3, 0x91, 0xb9, 0xff, 0x16, 0xeb, 0xb2, 0x75, 0x71, 0x3e, 0x63, 0x34, 0xc0, 0xdd,
	0x92, 0x70, 0x37, 0xc8, 0x62, 0x06, 0x38, 0xe9, 0x09, 0xb6, 0x17, 0xbf, 0x35, 0x5e, 0x93, 0x0f,
	0x08, 0x8f, 0xdf, 0x73, 0x82, 0x4c, 0x9c, 0x5d, 0xbe, 0x1f, 0xc0, 0xd9, 0x6d, 0x62, 0x7a, 0x5d,
	0x72, 0x96, 0xc8, 0x4c, 0x56, 0x4e, 0xf2, 0x15, 0x61, 0xdc, 0x36, 0x11, 0xd1, 0x07, 0xcd, 0x25,
	0xe9, 0x88, 0x22, 0xcb, 0x1c, 0x0f, 0x84, 0x37, 0x25, 0xa1, 0x41, 0x58, 0x06, 0x42, 0xb8, 0xd1,
	0x6c, 0x2f, 0x9a, 0xe2, 0x27, 0x84, 0x27, 0xa2, 0x29, 0x66, 0x23, 0xed, 0xf1, 0xee, 0x00, 0xd2,
	0x5e, 0x23, 0xd2, 0x05, 0x49, 0x3a, 0x47, 0x4a, 0xd9, 0x49, 0x57, 0x36, 0x0f, 0x9a, 0x1a, 0x3a,
	0x6c, 0x6a, 0xe8, 0x57, 0x53, 0x43, 0x6f, 0x5b, 0x5a, 0xee, 0xb0, 0xa5, 0xe5, 0x7e, 0xb4, 0xb4,
	0xdc, 0xd6, 0x92, 0xed, 0x84, 0xcf, 0xeb, 0x65, 0x7d, 0x5b, 0xd4, 0x3a, 0xf2, 0x3d, 0x82, 0x14,
	0x89, 0xbc, 0x2f, 0xff, 0x65, 0x0e, 0x77, 0x3d, 0x2b, 0x28, 0x17, 0xe4, 0x3f, 0xe2, 0xe2, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x81, 0x2c, 0xb9, 0x31, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListDrone Queries a list of Drone items.
	GetDrone(ctx context.Context, in *QueryGetDroneRequest, opts ...grpc.CallOption) (*QueryGetDroneResponse, error)
	// ListDrone defines the ListDrone RPC.
	ListDrone(ctx context.Context, in *QueryAllDroneRequest, opts ...grpc.CallOption) (*QueryAllDroneResponse, error)
	// ListMission Queries a list of Mission items.
	GetMission(ctx context.Context, in *QueryGetMissionRequest, opts ...grpc.CallOption) (*QueryGetMissionResponse, error)
	// ListMission defines the ListMission RPC.
	ListMission(ctx context.Context, in *QueryAllMissionRequest, opts ...grpc.CallOption) (*QueryAllMissionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/warzonecore.warzone.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDrone(ctx context.Context, in *QueryGetDroneRequest, opts ...grpc.CallOption) (*QueryGetDroneResponse, error) {
	out := new(QueryGetDroneResponse)
	err := c.cc.Invoke(ctx, "/warzonecore.warzone.v1.Query/GetDrone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDrone(ctx context.Context, in *QueryAllDroneRequest, opts ...grpc.CallOption) (*QueryAllDroneResponse, error) {
	out := new(QueryAllDroneResponse)
	err := c.cc.Invoke(ctx, "/warzonecore.warzone.v1.Query/ListDrone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetMission(ctx context.Context, in *QueryGetMissionRequest, opts ...grpc.CallOption) (*QueryGetMissionResponse, error) {
	out := new(QueryGetMissionResponse)
	err := c.cc.Invoke(ctx, "/warzonecore.warzone.v1.Query/GetMission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListMission(ctx context.Context, in *QueryAllMissionRequest, opts ...grpc.CallOption) (*QueryAllMissionResponse, error) {
	out := new(QueryAllMissionResponse)
	err := c.cc.Invoke(ctx, "/warzonecore.warzone.v1.Query/ListMission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListDrone Queries a list of Drone items.
	GetDrone(context.Context, *QueryGetDroneRequest) (*QueryGetDroneResponse, error)
	// ListDrone defines the ListDrone RPC.
	ListDrone(context.Context, *QueryAllDroneRequest) (*QueryAllDroneResponse, error)
	// ListMission Queries a list of Mission items.
	GetMission(context.Context, *QueryGetMissionRequest) (*QueryGetMissionResponse, error)
	// ListMission defines the ListMission RPC.
	ListMission(context.Context, *QueryAllMissionRequest) (*QueryAllMissionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetDrone(ctx context.Context, req *QueryGetDroneRequest) (*QueryGetDroneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrone not implemented")
}
func (*UnimplementedQueryServer) ListDrone(ctx context.Context, req *QueryAllDroneRequest) (*QueryAllDroneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDrone not implemented")
}
func (*UnimplementedQueryServer) GetMission(ctx context.Context, req *QueryGetMissionRequest) (*QueryGetMissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMission not implemented")
}
func (*UnimplementedQueryServer) ListMission(ctx context.Context, req *QueryAllMissionRequest) (*QueryAllMissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMission not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warzonecore.warzone.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warzonecore.warzone.v1.Query/GetDrone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDrone(ctx, req.(*QueryGetDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warzonecore.warzone.v1.Query/ListDrone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDrone(ctx, req.(*QueryAllDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warzonecore.warzone.v1.Query/GetMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMission(ctx, req.(*QueryGetMissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warzonecore.warzone.v1.Query/ListMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListMission(ctx, req.(*QueryAllMissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "warzonecore.warzone.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetDrone",
			Handler:    _Query_GetDrone_Handler,
		},
		{
			MethodName: "ListDrone",
			Handler:    _Query_ListDrone_Handler,
		},
		{
			MethodName: "GetMission",
			Handler:    _Query_GetMission_Handler,
		},
		{
			MethodName: "ListMission",
			Handler:    _Query_ListMission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warzonecore/warzone/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDroneRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDroneRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDroneRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DroneId) > 0 {
		i -= len(m.DroneId)
		copy(dAtA[i:], m.DroneId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DroneId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDroneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDroneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDroneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Drone.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDroneRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDroneRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDroneRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDroneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDroneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDroneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Drone) > 0 {
		for iNdEx := len(m.Drone) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Drone[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMissionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMissionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMissionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMissionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMissionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMissionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Mission.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMissionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMissionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMissionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMissionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMissionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMissionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Mission) > 0 {
		for iNdEx := len(m.Mission) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Mission[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDroneRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DroneId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDroneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Drone.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDroneRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDroneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Drone) > 0 {
		for _, e := range m.Drone {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMissionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetMissionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Mission.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMissionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMissionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Mission) > 0 {
		for _, e := range m.Mission {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDroneRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDroneRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDroneRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DroneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DroneId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDroneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDroneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDroneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Drone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Drone.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDroneRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDroneRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDroneRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDroneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDroneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDroneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Drone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Drone = append(m.Drone, Drone{})
			if err := m.Drone[len(m.Drone)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMissionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMissionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMissionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMissionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMissionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMissionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Mission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMissionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMissionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMissionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMissionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMissionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMissionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mission = append(m.Mission, Mission{})
			if err := m.Mission[len(m.Mission)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
