# Estagio de compilacao
FROM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o test-client ./test-client/main.go

# Estagio de execucao
FROM alpine:latest
RUN apk --no-cache add bash
WORKDIR /root/
COPY --from=builder /app/test-client .
ENTRYPOINT ["./test-client"]